version: '3.9'

services:
  flask-service:
    build:
      context: ./flask-service
    ports:
      - "1234:1234"
    networks:
      - app-network

  sidecar:
    image: envoyproxy/envoy:v1.23.0
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - ./sidecar/envoy-config.yaml:/etc/envoy/envoy.yaml

networks:
  app-network:
    driver: bridge
