version: '3.9'

services:
  flask-service:
    build:
      context: ./flask-service
    ports:
      - "1234:1234"   # Der Flask-Service wird auf Port 1234 des Hosts erreichbar gemacht
    networks:
      app-network:
        aliases:
          - flask-microservice  # Alias, damit der Dienst auch unter diesem Namen gefunden wird

  nginx-sidecar:
    build:
      context: ./nginx
    ports:
      - "8080:8080"  # Der Sidecar-Proxy ist auf Port 8080 erreichbar
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
