services:
  flask-service:
    build:
      context: ./flask-service
    ports:
      - "1235:1234"   # Der Flask-Service wird auf Port 1235 des Hosts erreichbar gemacht
    networks:
      - app-network

  nginx-sidecar:
    build:
      context: ./nginx
    ports:
      - "8080:8080"  # Der Sidecar-Proxy ist auf Port 8080 erreichbar
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
