version: '3.9'

services:
  flask-service:
    build:
      context: ./flask-service
    ports:
      - "1234:1234"   # Set external and internal ports 1234 for the flask server
    networks:
      app-network:
        aliases:
          - flask-microservice  # Alias to find the service with this name

  nginx-sidecar:
    build:
      context: ./nginx
    ports:
      - "8080:8080"  # Set external and internal ports 8080 for the sidecar-proxy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
